[package]
name = "cosmic-mime-apps"
description = "Parse and update xdg mimeapps.list files to manage default apps"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
freedesktop-desktop-entry = "0.7.19"
mime = "0.3.17"
quick-xml = "0.38"
xdg = "3.0"
